### PR TITLE
Add support to Datasource and Web Sessions conditions

### PR DESCRIPTION
**Pull request by aljesusg**
This is required by ManageIQ/manageiq#16125 and ManageIQ/manageiq#16113 to generate the conditions.

cc @josejulio 
https://issues.jboss.org/browse/HAWKULAR-1255

### CODE REVIEW

**Comment by aljesusg** [comment]
@lucasponce What do you think about have the alerts of DataSource mw_ds_average_get_time, mw_ds_average_creation_time and mw_ds_max_wait_time like a Rate type instead threshold?

**Comment by aljesusg** [comment]
@miq-bot add_label wip

**Comment by lucasponce** [comment]
> @lucasponce What do you think about have the alerts of DataSource mw_ds_average_get_time, mw_ds_average_creation_time and mw_ds_max_wait_time like a Rate type instead threshold?

It might sense to use a rate or threshold, as behaviour are different in any case, I woud ask in the JIRA linnking the PM to confirm requeriment.

**Comment by aljesusg** [comment]
@miq-bot remove_label wip

**Comment by aljesusg** [comment]
@lucasponce John told me in JIRA that we have to do with threshold. Can you review this PR? We need to request the merge in the UI ManageIQ/manageiq-ui-classic#2309

**Comment by aljesusg** [comment]
@miq-bot assign @abonas

**Comment by aljesusg** [comment]
@miq-bot add_label alerts, enhancement

**Comment by mtho11** [comment]
Thanks @lucasponce

**Comment by mtho11** [comment]
Ok since @abonas is out, I'll self-assign and merge.

**Comment by aljesusg** [comment]
Thanks @mtho11 for merge

**Pull request merged**
