### PR TITLE
[1511961] Middleware server reports fixed after introducing STI on MiddlewareServer

### PR DESCRIPTION
**Pull request by xeviknal**
Overriding `supported_models` let us tell to whole MiddlewareServer inheritance that their metrics are listed in the same metrics yaml: [product/live_metrics/middleware_server.yml](https://github.com/ManageIQ/manageiq/blob/master/product/live_metrics/middleware_server.yaml).

Since right now there aren't differences - regarding to live metrics - between EAP/Wildfly there is no need to split file into 3 different ones. When new metrics introduces for only one of the middleware servers kinds, then would be time to split it.

### CODE REVIEW

**Comment by abonas** [comment]
please change the title and the commit message to be explanatory that it fixes the problem, right now it sounds like the bug itself ("error ....")

**Comment by cfcosta** [comment]
I don't get it, what is expected to change with this? Can you give it more context?

**Comment by xeviknal** [comment]
sure @cfcosta. When capturing live_metrics for an entity in MIQ we are calling [this](https://github.com/ManageIQ/manageiq/blob/master/app/models/mixins/live_metrics_mixin.rb#L61) which is calling this yaml parsing [here](https://github.com/ManageIQ/manageiq/blob/master/app/models/mixins/live_metrics_mixin.rb#L72).

`load_live_metrics_config` is looking a yml file within 'products/live_metrics' folder. Specifically, is looking up for a file named as the instance class name ([here](https://github.com/ManageIQ/manageiq/blob/master/app/models/mixins/live_metrics_mixin.rb#L58)).

Since in the PR #60 were introduced a STI on MIddlewareServer, now there are two new kids on the neighbourhood: MiddlewareServerWildfly and MiddlewareServerEap. Then, when  `load_live_metrics_config` looks for the yaml name, it finds `middleware_server_wildfly` and `middleware_server_eap` instead of `middleware_server`.  And the files for children in the inheritance are not defined on core repo ([here](https://github.com/ManageIQ/manageiq/tree/master/product/live_metrics)).

**Comment by israel-hdez** [comment]
@xeviknal Can you add the bugzilla link to the main PR description?

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 83d9f0e5e91581c9ef675ed425b3a1642af99290
Author: Cainã Costa <me@cfcosta.com>
Date:   Wed Nov 15 14:07:37 2017 -0200

    Merge pull request #106 from xeviknal/1510421
    
    [1511961] Middleware server reports fixed after introducing STI on MiddlewareServer
    (cherry picked from commit f16422123da304f70bf4f7ad6893b4ba681995c0)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1514124
```

**Pull request merged**
