### PR TITLE
Missed  "install" in dnf command in system dependencies installation

### PR DESCRIPTION
**Pull request by aljesusg**
In the getting Started md is missed the "install" in the dnf command.

### CODE REVIEW

**Comment by aljesusg** [comment]
@miq-bot add_label documentation

**Comment by abonas** [comment]
@tumido @cfcosta please review

**Comment by mtho11** [comment]
Thanks for the catch @aljesusg

**Comment by abonas** [comment]
bad refresh, @mtho11 thanks for taking care of it

**Comment by aljesusg** [comment]
Thanks @mtho11 for merge.

**Pull request merged**
