### PR TITLE
Move dependency from manageiq-gems-pending

### PR DESCRIPTION
**Pull request by bdunne**
Add runtime dependency on hawkular-client.

### CODE REVIEW

**Comment by abonas** [comment]
we need to see what is the right approach here as 2 providers depend on this gem, so placing it here requires discussion

**Comment by bdunne** [comment]
@abonas What is the other provider?  It uses the hawkular-client gem directly?
Also, any idea why the tests failed with VCR issues?  It looks like master is green.

**Comment by abonas** [comment]
@bdunne kubernetes/openshift

**Comment by abonas** [comment]
cc @moolitayer

**Comment by moolitayer** [comment]
cc @simon3z

**Comment by moolitayer** [comment]
@bdunne as hawkular-client is being consumed by other components won't this make dependencies more complex?

**Comment by bdunne** [comment]
@moolitayer It may, but there are better ways to simplify the dependency relationship.

**Comment by bdunne** [comment]
@Jiri-Kremser It will fail to bundle in the `manageiq` repo if these two repos have incompatible requirements.  

However, I think the kubernetes provider should depend on the hawkuar provider and move the minimal amount of connection logic in the kubernetes repo to this repo.  Then the dependency on hawkular-client is only here.

**Comment by moolitayer** [comment]
If I understand currently the plan is indeed to move all kubernetes and openshift code dealing with hawkular to this repo (under the Datawarehouse manager) but that will not happen anytime soon.

In the mean time I didn't understand why we are splitting the dependency.
We will potentially need the two teams to be aware of upgrades - in that case I would expect the shared code not to be in the gems.

@bdunne I'm sure you have a reason for doing this so can you please explain?

**Comment by israel-hdez** [comment]
@Jiri-Kremser It is supposed to make things easier. Let's try, and refine if needed.

**Comment by bdunne** [comment]
@moolitayer The dependency is currently on `manageiq-gems-pending` (a technical debt repo) and doesn't belong there since nothing in manageiq-gems-pending requires it.  This repo does require the gem and should list it as a dependency.

**Comment by jrafanie** [comment]
> In the mean time I didn't understand why we are splitting the dependency.
> We will potentially need the two teams to be aware of upgrades - in that case I would expect the shared code not to be in the gems.

@moolitayer It's about being explicit about dependencies.  As we extract things, the consumer of various gem dependencies become harder to find, so those dependencies need to be moved to where they're used.  It might seem like more work to maintain gem dependencies in multiple places but it's better to be explicit than to have no idea who's using a gem. 

For example, if I need to bump a gem version for ruby 2.4 and it's specified in manageiq-gems-pending but not used there, it's unclear to me how I know if the new gem version works wherever in all places.  Do I bundle and grep through my entire ruby .gem directory to find any callers of the gem?  What if I grep wrong?

**Comment by bdunne** [comment]
:turtle: bump
cc @Fryguy

**Pull request merged**
