### PR TITLE
Datawarehouse: Retrieve resolved alerts from hawkular

### PR DESCRIPTION
**Pull request by moolitayer**
Retrieve resolved alerts from hawkular.
To see the type of hawkular alerts we plan to use with this see [this](https://github.com/moolitayer/hawkular-curl-examples/tree/4a22cbc4bf6e7f1ae7ae0e617eb730247c7d19aa/ops-example)

Moved from https://github.com/ManageIQ/manageiq/pull/14299

### CODE REVIEW

**Comment by moolitayer** [comment]
@simon3z please review

**Comment by simon3z** [comment]
> @simon3z please review

@moolitayer can you get a couple of reviews from the team? cc @cben @enoodle

**Comment by moolitayer** [comment]
@simon3z By the way this was already acked by @jshaughn @yaacov
(More reviews are welcome)

**Comment by moolitayer** [comment]
@abonas could you please review/merge?

**Comment by lucasponce** [comment]
In the PR there are changes in the mixin and specific changes for the datawarehouse provider.
The mixin is not yet used by Middleware provider, so those are safe as thouse should have not impact in MW work.

**Comment by Fryguy** [comment]
@miq-bot assign abonas

**Comment by abonas** [comment]
@moolitayer is it fine/yes or fine/no?

**Comment by moolitayer** [comment]
@miq-bot add_label fine/no

cc @simon3z

**Pull request merged**
