### PR TITLE
convert cassettes to webmock-2.0 compatible format

### PR DESCRIPTION
**Pull request by durandom**
via https://gist.github.com/glaszig/9170b1cf2186674faeead74a68606c5d
needed for ManageIQ/manageiq#14270

cc @jrafanie

### CODE REVIEW

**Comment by Jiri-Kremser** [comment]
currently the tests are red, could you pls review @cfcosta ?

**Comment by durandom** [comment]
yeah, I should have mentioned that this PR will turn the specs green again once https://github.com/ManageIQ/manageiq/pull/14270 is merged

**Comment by jrafanie** [comment]
@durandom ManageIQ/manageiq#14270 is merged, please rekick this build

**Comment by durandom** [comment]
@Jiri-Kremser please merge

**Pull request merged**
